+JobFlavour   = "espresso"

+OnExitHold   = ExitStatus != 0 

periodic_release =  (NumJobStarts < 4) && ((CurrentTime - EnteredCurrentStatus) > 60) 

getenv        = True 
input         = /afs/cern.ch/user/r/rdalialu/.dasmaps/das_maps_dbs_prod.js 
executable    = /afs/cern.ch/user/r/rdalialu/eos/CMSSW_10_6_29/src/flashgg/CondorTest/runJobs0.sh
arguments     = $(ProcId)
output        = /afs/cern.ch/user/r/rdalialu/eos/CMSSW_10_6_29/src/flashgg/CondorTest/runJobs0_$(ClusterId).$(ProcId).out
error         = /afs/cern.ch/user/r/rdalialu/eos/CMSSW_10_6_29/src/flashgg/CondorTest/runJobs0_$(ClusterId).$(ProcId).err
log           = /afs/cern.ch/user/r/rdalialu/eos/CMSSW_10_6_29/src/flashgg/CondorTest/runJobs0_$(ClusterId).$(ProcId)_htc.log

RequestCpus   = 1
max_retries   = 2
queue 2 
